"""empty message

Revision ID: 56ea7744bfc0
Revises: 2ef0d4884385
Create Date: 2016-05-16 21:22:21.151054

"""

# revision identifiers, used by Alembic.
revision = '56ea7744bfc0'
down_revision = '2ef0d4884385'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('province', sa.String(length=64), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('district', sa.String(length=64), nullable=False),
    sa.Column('street', sa.String(length=128), nullable=False),
    sa.Column('zip_code', sa.String(length=64), nullable=False),
    sa.Column('reciplents', sa.String(length=64), nullable=False),
    sa.Column('phone_number', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('addresses')
    ### end Alembic commands ###
