"""add_order_table

Revision ID: 887e1c80c568
Revises: c05a550c4f9a
Create Date: 2016-06-22 20:39:40.223605

"""

# revision identifiers, used by Alembic.
revision = '887e1c80c568'
down_revision = 'c05a550c4f9a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('total_sum', sa.Float(), nullable=False),
    sa.Column('province', sa.String(length=64), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('district', sa.String(length=64), nullable=False),
    sa.Column('street', sa.String(length=128), nullable=False),
    sa.Column('zip_code', sa.String(length=64), nullable=False),
    sa.Column('reciplents', sa.String(length=64), nullable=False),
    sa.Column('phone_number', sa.String(length=64), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('order_datetime', sa.DateTime(), nullable=True),
    sa.Column('deliver_date', sa.Date(), nullable=True),
    sa.Column('deliver_time', sa.Integer(), nullable=True),
    sa.Column('order_status', sa.Integer(), nullable=True),
    sa.Column('shipping_status', sa.Integer(), nullable=True),
    sa.Column('pay_status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_table('order_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_products')
    op.drop_table('orders')
    ### end Alembic commands ###
