"""empty message

Revision ID: c05a550c4f9a
Revises: 8fa75438ed64
Create Date: 2016-05-25 21:15:58.334210

"""

# revision identifiers, used by Alembic.
revision = 'c05a550c4f9a'
down_revision = '8fa75438ed64'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address_default_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'address_default_id')
    ### end Alembic commands ###
